
export type TestQuestionType = 'single-choice' | 'multi-choice';

// This defines a single, scorable test question
export interface TestQuestion {
  id: string;
  label: string; // The question text
  type: TestQuestionType;
  options: string[]; // The list of possible answers

  /**
   * The correct answer(s) for this question.
   * - For 'single-choice', this will be a single string.
   * - For 'multi-choice', this will be an array of strings.
   */
  correctAnswer: string | string[];

  /**
   * The number of points this question is worth. Optional.
   */
  points?: number;
  category: string;

  /**
   * Validation rules, e.g., to make a question mandatory.
   */
  validation?: {
    required?: boolean;
  };
}

// This defines the entire knowledge test for a job
// export interface TestAssessment {
//   jobId: number;
//   title: string;
//   questions: TestQuestion[];
// }

// The structure of an assessment created by HR for a specific job
// export interface CreatedAssesment {
//   jobId: number; // Primary Key
//   title: string;
//   topics:string[];
//   numberOfQuestions:number;
//   questions: TestQuestion[];
// }

export interface AssignedAssessment {
  candidateId: number; // Points to a Candidate's 'id'
  assessmentId: number; // Points to a CreatedAssessment's 'id'
}
export interface CreatedAssesment {
  id?: number; // Primary Key
  title: string;
  topics: string[];
  numberOfQuestions: number;
  duration:number; //time in minutes
  questionIds: string[]; // Changed from 'questions' to 'questionIds'
}

export interface PaginatedAssessmentsResponse {
  data: CreatedAssesment[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

export interface AssessmentRequest {
  title:string;
  topics: string[];
  numberOfQuestions: number;
  duration:number//time in minutes
}

// The raw answer for a single question, sent from the frontend
interface UserAnswer {
  questionId: string;
  selectedAnswer: string|string[];
}

// In your types/assessment.ts file

export interface OverallAssessmentStats {
  totalTemplates: number;     // Total number of assessment templates created
  totalAssignments: number;   // Total times assessments have been assigned
  totalCompletions: number;   // Total assessments that have been submitted
  completionRate: number;     // Percentage of assigned assessments that were completed
  overallAverageScore: number; // The average score across all completed assessments
}


// The entire payload sent from the frontend upon submission
export interface AssessmentSubmission {
  id?: number;
  candidateId: number;
  answers: UserAnswer[];
}

// The final, calculated result that gets stored in the database
export interface AssessmentResult {
  id?: number; // This will be auto-generated by Dexie
  assessmentId: number;
  candidateId: number;
  score: number;
  totalQuestions: number;
  submittedAt: Date;
  answers: UserAnswer[];
}
// --- In your types file ---

export interface AssessmentSummary {
  id: number;
  attemptsCount: number;
  averageScore: number; // Will be a percentage (e.g., 75.5)
  passedCount: number;
  failedCount: number;
  highestScore: number; // Will be a percentage
  lowestScore: number; // Will be a percentage
  results: AssessmentResult[]; // The raw list of individual results
}

